/* Action types */
export const actionTypes = {
  USERS_SAMPLE_FETCH: 'USERS/SAMPLE_FETCH',
  USERS_SAMPLE_FETCH_SUCCESS: 'USERS/SAMPLE_FETCH_SUCCESS',
  USERS_SAMPLE_FETCH_ERROR: 'USERS/SAMPLE_FETCH_ERROR'
};
